### PR TITLE
Create Homepage

### PR DESCRIPTION
**Pull request by Nanokwok**
# Merge Request: Create Homepage

## Overview
This merge request introduces the newly designed homepage for the MoneyMap application, which includes several enhancements and features aimed at improving user experience and engagement.

### Main Content Section
- **Text Section:**
  - Added a prominent heading with dynamic font sizes for better visibility:
    - "Better Plan with MoneyMap" using two different fonts and colors.
- **Coin Image Section:**
  - Introduced a coin image that scales with the screen size to enhance the visual appeal.

### Features Section
- **Card Layout:**
  - Created a three-column card layout for displaying key features:
    - **Card 1: Goals**
      - Introduced a card that helps users define and track their financial goals.
      - Includes a background vector image and a rotation effect on hover.
    - **Card 2: Income and Expenses**
      - Designed to log income and expenses with a background image that translates upwards on hover.
    - **Card 3: Financial History**
      - Allows users to review their past financial activities.
      - Added a rotating icon on hover for better interaction feedback.

### Additional Section
- **Why Choose MoneyMap:**
  - Introduced a new section emphasizing the benefits of using MoneyMap.
  - Includes engaging text and stylized fonts for emphasis.
  - Added two new cards detailing:
    - **Goal-Focused Savings**: Describes how users can save for specific goals.
    - **Real-Time Progress**: Explains dynamic tracking of savings plans.

### Styling and Responsiveness
- Ensured all sections are responsive and visually appealing across different screen sizes.
- Utilized Tailwind CSS for utility-first styling, enhancing the overall UI/UX.

## Conclusion
This merge request aims to enhance the homepage with a more engaging layout, clear messaging, and interactive elements that invite users to explore the features of MoneyMap.

### CODE REVIEW

**Comment by Nanokwok** [comment]
### Updates in This Pull Request

#### Summary of Changes:
- **Change Banner Background:** Updated the background of the banner for better visibility and aesthetics. (`95745a3`)
- **Add Picture for Homepage:** Included a new image on the homepage to enhance the visual appeal. (`06a8f2f`)
- **Add Footer to Homepage:** Implemented a footer section on the homepage for improved navigation and information. (`009429d`)
- **Remove Shadow for Card 3:** Removed the shadow effect on Card 3 to achieve a cleaner look. (`f6a9dd2`)
- **Change Color on Hover:** Modified the hover color for interactive elements to improve user experience. (`9bec964`)
- **Add Pointer in "Why Choose MoneyMap" Section:** Included a pointer to emphasize important information in this section. 

### Notes:
- Please review and let me know if any further adjustments are needed!

Thank you!

**Review by colarrbear — APPROVED** [review]
I've checked. Homepage look nice to me. Keep up the good work!

**Review by JaofourthsOhappy — APPROVED** [review]
Screenshot 2567-10-13 at 20 29 21
good!!

**Review by KikyoBRV — COMMENTED** [review]
Home page looking great.

**Pull request merged**
